#!/bin/sh
#

## Optimise
grunt optim

## Set var
TIMESTAMP=$(date +%Y%m%d%H%M%S)

# Make a new releases folder
ssh $USERNAME@$HOST "mkdir $STAGING_DEPLOY_TO/releases/$TIMESTAMP"

# Copy files
rsync -avz -e "ssh" --exclude=".git" ~/clone/web/ $USERNAME@$HOST:$STAGING_DEPLOY_TO/releases/$TIMESTAMP

# Copy files
rsync -avz -e "ssh" ~/clone/web/ $USERNAME@$HOST:$STAGING_DEPLOY_TO/releases/$TIMESTAMP
rsync -avz -e "ssh" ~/clone/config/staging.htaccess $USERNAME@$HOST:$STAGING_DEPLOY_TO/releases/$TIMESTAMP/.htaccess
rsync -avz -e "ssh" ~/clone/config/staging.wp-config.php $USERNAME@$HOST:$STAGING_DEPLOY_TO/releases/$TIMESTAMP/wp-config.php

# Copy API
scp -c blowfish -C -r ~/clone/api $USERNAME@$HOST:$STAGING_DEPLOY_TO/releases/$TIMESTAMP/api

# Symlink shared folders
ssh $USERNAME@$HOST "cd $STAGING_DEPLOY_TO/releases/$TIMESTAMP/content/;ln -s $STAGING_SHARED/uploads uploads"

#ln -s $STAGING_SHARED/logs $STAGING_DEPLOY_TO/$TIMESTAMP/content/logs

# Update app version
ssh $USERNAME@$HOST "rm -rf $STAGING_CURRENT;ln -s $STAGING_DEPLOY_TO/releases/$TIMESTAMP/ $STAGING_CURRENT"

# Cleanup
