#!/bin/sh
#
# Quality Assurance tests

# Install coding standards
echo "Installing coding standards..."
./vendor/bin/phpcs --config-set installed_paths $(pwd)/vendor/wp-coding-standards/wpcs/

# Run tests
echo "Running WordPress PHP Coding Standards test"
# Uncomment following to run tests.
#./vendor/bin/phpcs --standard="WordPress" web/content/themes/ --extensions="php" --ignore="index.php,node_modules/,twentysixteen/"
# grunt test
